version: "3.8"

services:
  mongo:
    image: mongo:4.4.5
    container_name: mongo
    ports:
      - 27017:27017
  hex-backend:
    image: $REGISTRY_PROJECT/app-name
    container_name: app-name
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/app-name
      - MONGO_DB_NAME=app-name
      - JWT_SECRET=jwt-secret
      - JWT_TTL=1h
      - CHALLENGE_TTL=1s
    depends_on:
      - fake-service
      - mongo
